server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
logging:
  level:
    '[org.springframework.boot.web]': INFO